ado/examples/blog/urls.py
from django.urls import path, re_path

from ado.examples.blog import feeds
from ado.examples.blog import views
from ado import menus


urlpatterns = [
    path('', views.blog_index, name='blog-index'),

    # Main URLS
    re_path(r'^(?P<year>\d{4})/(?P<month>\w{3})/$', views.month_archive, name='blog-month-archive'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{1,2})/$', views.day_archive, name='blog-day-archive'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{1,2})/(?P<slug>[\w-]+)/$', views.entry_detail, name='blog-entry-view'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<slug>[\w-]+)/$', views.entry_month_detail),

    # Alternative URLS with number format for month
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', views.month_archive_alt),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{1,2})/$', views.day_archive_alt),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{1,2})/(?P<slug>[\w-]+)/$', views.entry_detail_alt),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[\w-]+)/$', views.entry_month_detail_alt),

    # Feeds
    path('feed/', feeds.LatestEntriesFeed(), name='blog-feed'),
    path('feed/rss/', feeds.LatestEntriesFeed(), name='blog-feed-rss'),
    path('feed/atom/', feeds.AtomLatestEntriesFeed(), name='blog-feed-atom'),
]

menus.register_url('Blog', name='blog-index')

ado/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    # App examples
    path('pages/', include('ado.examples.pages.urls')),
    path('portfolio/', include('ado.examples.portfolio.urls')),
    path('artists/', include('ado.examples.artists.urls')),
    path('exhibitions/', include('ado.examples.exhibitions.urls')),
    path('blog/', include('ado.examples.blog.urls')),

    # Admin
    path('customadmin/', include('ado.customadmin.urls')),
    path('media/', include('ado.media.urls')),
    path('admin/', admin.site.urls),
]

# MEDIA For Development Server
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT,
                      show_indexes=True)

ado/examples/blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse
from django.utils.encoding import smart_text
from django.utils.text import Truncator
from django.utils.html import strip_tags
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

from taggit.managers import TaggableManager
from autoslug import AutoSlugField
from positions.fields import PositionField
from ado.content.models import ContentItem


class CategoryQuerySet(models.QuerySet):
    def in_use(self):
        return self.filter(entries__isnull=False).distinct()


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(
        populate_from='name',
        max_length=200,
        unique=True,
        editable=False,
        help_text='Unique text identifier used in urls.')

    objects = CategoryQuerySet.as_manager()

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class EntryQuerySet(models.QuerySet):
    def published(self):
        now = timezone.now()
        return self.filter(published=True, pub_date__lte=now)

    def recent(self, count=10):
        return self.published()[:count]


class Entry(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(
        populate_from='title',
        max_length=200,
        unique=True,
        help_text='Unique text identifier used in urls.')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(
        'Date published',
        default=timezone.now,
        db_index=True,
        help_text='Date you would like this entry to go live on the site.')
    published = models.BooleanField(
        default=True,
        help_text='Select to publish on the site.')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(
        Category,
        blank=True,
        related_name='entries')
    related_entries = models.ManyToManyField(
        'self',
        blank=True,
        symmetrical=False)
    tags = TaggableManager(blank=True)

    objects = EntryQuerySet.as_manager()

    class Meta:
        verbose_name = 'Blog Entry'
        verbose_name_plural = 'Blog Entries'
        ordering = ('-pub_date',)
        get_latest_by = 'pub_date'

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        if settings.USE_TZ:
            tz = timezone.get_default_timezone()
            pub_date = timezone.localtime(self.pub_date, tz)
        else:
            pub_date = self.pub_date
        args = pub_date.strftime("%Y %b %d").split() + [self.slug]
        return reverse('blog-entry-view', args=args)

    @property
    def author_name(self):
        author = self.author
        name = author.get_full_name()
        return name or author.username or author.email

    @property
    def excerpt(self, trunc=80):
        text = ' '.join([item.text for item in self.content.exclude(text='')])
        text = smart_text(text, encoding="utf-8")
        text = strip_tags(text)
        return Truncator(text).words(trunc, html=False, truncate=' ...')


class EntryContent(ContentItem):
    related_model = Entry


class Link(models.Model):
    url = models.URLField(max_length=255)
    title = models.CharField(max_length=255)
    position = PositionField()

    class Meta:
        ordering = ('position',)

    def __str__(self):
        return self.title

ado/examples/blog/views.py
from django.db.models import Q
from django.views.generic import (
        ListView, MonthArchiveView, DayArchiveView, DateDetailView)
from django.views.generic.detail import (
        BaseDetailView, SingleObjectTemplateResponseMixin)
from django.views.generic.dates import (
        DateMixin, YearMixin, MonthMixin, _date_from_string)
from ado.examples.blog.models import Entry


import logging
log = logging.getLogger(__name__)


def _month_bounds(date):
    """
    Helper: return the first and last days of the month for the given date.
    """
    first_day = date.replace(day=1)
    if first_day.month == 12:
        last_day = first_day.replace(year=first_day.year + 1, month=1)
    else:
        last_day = first_day.replace(month=first_day.month + 1)

    return first_day, last_day


class BlogIndexMixin(object):
    template_name = 'blog/index.html'
    date_field = 'pub_date'

    def get_queryset(self):
        return self.filter_queryset(
                Entry.objects.published()
                     .select_related()
                     .prefetch_related('categories', 'tags'))

    def filter_queryset(self, qs):
        search_query = self.request.GET.get('q')
        if search_query:
            qs = qs.filter(
                Q(content__text__icontains=search_query) |
                Q(title__icontains=search_query))
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tags__name=tag)

        category_slug = self.get_category_slug()
        if category_slug:
            qs = qs.filter(categories__slug=category_slug)

        author_id = self.get_author_id()
        if author_id:
            qs = qs.filter(author=author_id)

        return qs

    def get_author_id(self):
        author_id = self.request.GET.get('author', '')
        try:
            author_id = int(author_id)
        except ValueError:
            author_id = None
        return author_id

    def get_category_slug(self):
        return self.request.GET.get('cat')


class BlogIndexView(BlogIndexMixin, ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'author_id': self.get_author_id(),
            'category_slug': self.request.GET.get('cat'),
            'current_tag': self.request.GET.get('tag'),
        })
        return context


blog_index = BlogIndexView.as_view()


class BlogMonthView(BlogIndexMixin, MonthArchiveView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'author_id': self.get_author_id(),
            'category_slug': self.request.GET.get('cat'),
            'current_tag': self.request.GET.get('tag'),
        })
        return context


month_archive = BlogMonthView.as_view()
month_archive_alt = BlogMonthView.as_view(month_format='%m')


class BlogDayView(BlogIndexMixin, DayArchiveView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'author_id': self.get_author_id(),
            'category_slug': self.request.GET.get('cat'),
            'current_tag': self.request.GET.get('tag'),
        })
        return context


day_archive = BlogDayView.as_view()
day_archive_alt = BlogDayView.as_view(month_format='%m')


class BaseMonthDetailView(YearMixin, MonthMixin, DateMixin, BaseDetailView):
    def get_object(self, queryset=None):
        year = self.get_year()
        month = self.get_month()

        qs = self.get_queryset()

        date_field = self.get_date_field()
        date = _date_from_string(year, self.get_year_format(),
                                 month, self.get_month_format())

        # Construct a date-range lookup.
        first_day, last_day = _month_bounds(date)
        lookup_kwargs = {
            '%s__gte' % date_field: first_day,
            '%s__lt' % date_field: last_day,
        }

        qs = qs.filter(**lookup_kwargs)

        return super().get_object(queryset=qs)


class BlogMonthDetailView(SingleObjectTemplateResponseMixin,
                          BaseMonthDetailView):
    date_field = 'pub_date'

    def get_queryset(self):
        return Entry.objects.published().select_related()


entry_month_detail = BlogMonthDetailView.as_view()
entry_month_detail_alt = BlogMonthDetailView.as_view(month_format='%m')


class EntryDetailView(DateDetailView):
    date_field = 'pub_date'

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated and user.is_staff:
            qs = Entry.objects.all().select_related()
        else:
            qs = Entry.objects.published().select_related()
        return qs


entry_detail = EntryDetailView.as_view()
entry_detail_alt = EntryDetailView.as_view(month_format='%m')

ado/examples/blog/templates/blog/base.html
{% extends "base.html" %}{% load blog %}

{% block extrahead %}
<link rel="alternate" type="application/rss+xml" title="Feed of latest entries" href="{% url 'blog-feed' %}" />
{% endblock %}

{% block content %}
{% block blog-sidebar %}
    <div id="blog-sidebar" class="blog-sidebar sidebar">
    <h4><a href="{% url 'blog-feed' %}">RSS Feed</a></h4>

    {% blog_category_list %}
    
    {% blog_link_list %}

    {% blog_author_list %}

    {% blog_archive_list %}

    </div>
{% endblock %}

{% endblock %}

ado/examples/blog/templates/blog/entry_detail.html
{% extends "blog/base.html" %}
{% load blog thumbnailer %}

{% block extrahead %}
{{block.super}}

<script type="text/javascript">
$(function() {
    var $link = $('#main-menu a[href={% url 'blog-index' %}]')
    if ($link.length < 1)
        $link = $('#main-menu a[href={% url 'blog-index' %}]')
    $link.addClass('active');    
});
</script>
{% endblock %}


{% block content %}

{{ block.super }}

<div class="blog-entry">
    <h2><a href="{{entry.get_absolute_url}}" class="highlight">{{entry.title}}</a></h2>
    <div class="info">
        {{entry.pub_date|date:"n/d/Y"}} | 
        posted by {{entry.author.get_full_name|default:entry.author.username}}
        {% for cat in entry.categories.all %}
        <a href="{% url 'blog-index' %}?cat={{cat.slug}}">{{cat}}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
        | <a href="{{entry.get_absolute_url}}">Permalink</a>
    </div>

    <div class="body">
        {% for item in entry.content.all %}
        {% if item.text %}{{item.text|safe}}{% endif %}
        {% if item.image %}{% thumbnail item.image.filename "200x200" as thumb %}<p><img src="{{thumb.url}}" width="{{thumb.width}}" /></p>{% endthumbnail %}{% endif %}
        {% if item.video %}<p>{{item.video.embed|safe}}</p>{% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

ado/examples/blog/templates/blog/index.html
{% extends "blog/base.html" %}{% load blog %}

{% block title %}Blog | {{block.super}} {% endblock %}

{% block extrahead %}
{{ block.super }}

<script type="text/javascript">
$(function() {
    var $link = $('#main-menu a[href={% url 'blog-index' %}]')
    $link.addClass('active');
    {% if category %}
    $('.blog-categories a[rel={{category}}]').addClass('active');
    {% endif %}
    {% if month %}
    $('.blog-archive-list a[rel={{month.month}}_{{month.year}}]').addClass('active');
    {% endif %}
    {% if author_id %}
    $('.blog-authors a[rel={{author_id}}]').addClass('active');
    {% endif %}
});
</script>
{% endblock %}


{% block content %}

{{ block.super }}

<ul class="blog-index wrapper">
{% for entry in entry_list %}
    <li class="blog-entry{% if forloop.last %} last{% endif %}">
        <h2><a href="{{entry.get_absolute_url}}" class="highlight">{{entry.title}}</a></h2>
        <div class="info">
            {{entry.pub_date|date:"n/d/Y"}} | 
            posted by {{entry.author.get_full_name|default:entry.author.username}}
            {% for cat in entry.categories.all %}
            <a href="{% url 'blog-index' %}?cat={{cat.slug}}">{{cat}}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            | <a href="{{entry.get_absolute_url}}">Permalink</a>
        </div>

        <div class="body">
            {{ entry.excerpt|safe }}
        </div>
    </li>
{% endfor %}
</ul>
{% endblock %}